# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_docs_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='kind',
            field=models.CharField(choices=[('IMG', 'Imagen'), ('PDF', 'PDF'), ('WRD', 'WORD')], default='IMG', max_length=3),
        ),
    ]
