# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.CharField(default='video.png', max_length=200),
        ),
    ]
