# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
