# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_videos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
